# ~/.bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

#alias sudo='doas'
alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

export PATH="$HOME/.local/bin:$PATH"

eval "$(starship init bash)"
