# Hardware configuration for host.
#
# This file is normally automatically generated by `nixos-generate-config`.
# Since this is a bare-metal machine you should replace the contents of this
# file with the output of `nixos-generate-config` run on this machine. The
# example below assumes a disk layout identical to the one used for our VMs:
# a "nixos" root partition (ext4) and a "boot" EFI partition (vfat).
{ config, lib, pkgs, modulesPath, ... }:


